#!/bin/sh
#
# slug-case: change the case of each word to use slug format.
#
# Examples:
#
#   ```shell
#   $ echo "FooGooHoo" | slug-case
#   foogoohoo
#
#   $ echo "foo_goo_hoo" | slug-case
#   foo-goo-hoo
#
#   $ echo "can't stop won't stop" | slug-case
#   cant-stop-wont-stop
#   ```
#
# The script does this:
#
#   * Delete any contraction quote a.k.a. apostrophe.
#
#   * Translate any non-alphanumeric to a dash.
#
#   * Ensure only one dash in a row.
#
#   * Change case to lower case.
#
perl -pe "s/['’]//g; s/[^[:alnum:]]/-/g; s/--+/-/g; \$_=lc(\$_)"
