#!/bin/sh
#
# title-case: change the case of each word to use title format.
#
# Examples:
#
#   ```shell
#   $ echo "foo goo hoo" | title-case
#   Foo Goo Hoo
#
# The script does this:
#
#   * Convert the first letter of each word to upper-case.
#
#   * A word is defined by the perl `\w` regexp.
#
perl -pe 's/(\w)(\w*)/$1\u\L$2/g'

